# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = PKU-Hole
DESTDIR = ./x64/Debug
CONFIG += debug
LIBS += -L"." \
    -l/"$(INHERIT)/" \
    -l$(Qt_LIBS_) \
    -lC:/Users/19022/source/repos/PKU-Hole/lib/libjsond \
    -lC:/Users/19022/source/repos/PKU-Hole/lib/libcurl.dll.a
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
